-- Insert standard rejection reasons
INSERT INTO public.rejection_reasons (category, reason, is_candidate_rejection, display_order) VALUES
  ('skills', 'Missing required technical skills', false, 1),
  ('skills', 'Skill level insufficient for role', false, 2),
  ('experience', 'Insufficient years of experience', false, 3),
  ('experience', 'Experience not relevant to role', false, 4),
  ('experience', 'Overqualified for position', false, 5),
  ('salary', 'Salary expectations too high', false, 6),
  ('salary', 'Unable to match salary expectations', false, 7),
  ('location', 'Location not suitable', false, 8),
  ('location', 'Unable to relocate', false, 9),
  ('culture', 'Cultural fit concerns', false, 10),
  ('culture', 'Team fit concerns', false, 11),
  ('timing', 'Notice period too long', false, 12),
  ('timing', 'Role already filled', false, 13),
  ('other', 'Internal candidate preferred', false, 14),
  ('other', 'Role put on hold', false, 15),
  ('other', 'Budget constraints', false, 16),
  ('salary', 'Offer too low', true, 17),
  ('role', 'Role not as described', true, 18),
  ('culture', 'Company culture not suitable', true, 19),
  ('timing', 'Accepted another offer', true, 20),
  ('personal', 'Personal circumstances changed', true, 21),
  ('location', 'Commute too far', true, 22);