// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yoegksjmdtubnkgdtttj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvZWdrc2ptZHR1Ym5rZ2R0dHRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMTE3NzYsImV4cCI6MjA2ODU4Nzc3Nn0.HUXRJdpZSp3AIsCKY0Hb51tbCoMedLghXL17ctCOCvc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});